# N.B. there are NOOOO CHECKS IN PLACE currently!!!!
#     make sure your mapping is to a number within the size of the subnet!
#     and make sure the subnets you configure are within the containing subnet of 10.10.0.0/16
subnets:
  10.10.0.0/28: 3
  10.10.1.0/28: 4
  # 10.10.2.0/28: 6
